<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Arkos.Intelligence</RootNamespace>
    <AssemblyName>Arkos.Intelligence</AssemblyName>
  </PropertyGroup>
</Project>
